### PR TITLE
Allow to specify guest file permissions

### PR DESCRIPTION
**Pull request by pborzenkov**
Will be used by FKS to set permissions for files in projected volumes.

### CODE REVIEW

**Review by jipperinbham — COMMENTED** [review]
What are some example values?

**Comment by pborzenkov** [comment]
@jipperinbham 

> What are some example values?

Just usual Unix permissions bits, like `0600`.

**Comment by jipperinbham** [comment]
Gotcha, I'd maybe add some tests to verify the marshal/unmarshal does what we want. There's a comment on the k8s API docs about what is and isn't accepted based on content-type: 

> defaultMode is Optional: mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Defaults to 0644.

**Comment by pborzenkov** [comment]
@jipperinbham 

> Gotcha, I'd maybe add some tests to verify the marshal/unmarshal does what we want.

I'm not sure I follow. This is just an integer, what's to test here?

`flyctl` has its own `File` type used in `fly.toml` and there it makes sense to test that it deserializes correctly from, for example, `0o<num>` toml representation (toml has support for octals).

**Comment by jipperinbham** [comment]
https://go.dev/play/p/Q1m5nUdt5ol

**Comment by jipperinbham** [comment]
Yes, sorry I wasn't clear with the last comment. My concern is the confusion it could cause some users if they provided one value `0700` and then later got back another value even though it's the "same" one in a different form. I don't want to reinvent file permission definitions but I do think it'd be good to have a comment for the field explaining what it specifically is and the octal vs actual value.

**Comment by pborzenkov** [comment]
@jipperinbham Since we generate OpenAPI spec from the comments and the only integer form accepted by JSON is decimal, I don't think it makes sense to describe here what an octal and decimal form of the field can be, since the only way to specify it via the API is decimal.

I added a reference to `chmod(2)` to make it clear that these are the same permissions bits.

**Review by jipperinbham — APPROVED** [review]

**Pull request merged**
